theme: minima

title: Adam Catley
author: Adam Catley
email: contact@adamcatley.com
description: About me

twitter_username: adamcatley
github_username:  adamcatley
linkedin_username: adamcatley

google_analytics: UA-26205307-2
